---
- hosts: all
  vars:
    grid_admin_base_url: https://www.webscalenextadm.netapp.com/
    grid_user: root
    grid_pass: st0rageGr1D@beta
  gather_facts: no
  tasks:
  - name: Get user authorization token
    uri:
      url: "{{ grid_admin_base_url }}api/v3/authorize"
      method: POST
      body: {
        "username": "{{ grid_user }}",
        "password": "{{ grid_pass }}",
        "cookie": false,
        "csrfToken": false
      }
      body_format: json
      validate_certs: false
    register: auth
    no_log: false
  - name: print auth token
    debug:
      msg: "{{ auth.json.data }}"

