
---
- hosts: all
  gather_facts: no
  tasks:
  - name: Get user authorization token
    uri:
      url: "{{ grid_admin_base_url }}api/v3/authorize"
      method: POST
      body: {
        "username": "{{ grid_user }}",
        "password": "{{ grid_pass }}",
        "cookie": false,
        "csrfToken": false
      }
      body_format: json
      validate_certs: false
    register: auth
    no_log: false
  - name: print auth token
    debug:
      msg: "{{ auth.json.data }}"

  - name: update DNS servers
    netapp.storagegrid.nac_sg_grid_dns:
      api_url: "{{ grid_admin_base_url }}"
      auth_token: "{{ auth.json.data }}"
      validate_certs: false
      state: present
      dns_servers: "1.1.1.1,8.8.8.8"
