---
- hosts: localhost
  vars:
    grid_admin_base_url: https://sggmi-dev.dev.ausngs.netapp.au/api/v3
    grid_user: root
    grid_pass: netapp01
  gather_facts: no
  tasks:
  - name: Get user authorization token
    uri:
      url: "{{ grid_admin_base_url }}/authorize"
      method: POST
      body: {
        "accountId": "46746482220000154865",
        "username": "{{ grid_user }}",
        "password": "{{ grid_pass }}",
        "cookie": false,
        "csrfToken": false
      }
      body_format: json
      validate_certs: false
    register: auth
    no_log: false
  - name: print auth token
    debug:
      msg: "{{ auth.json.data }}"

  - name: create a s3 bucket
    netapp.storagegrid.na_sg_org_container:
      api_url: "{{ grid_admin_base_url }}"
      auth_token: "{{ auth.json.data }}"
      validate_certs: false
      state: present
      name: ansiblebucket1
